# Generated by Django 5.0.1 on 2024-01-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rolik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolik_num', models.PositiveIntegerField()),
                ('rolik_size', models.CharField(max_length=50)),
                ('rolik_color', models.CharField(choices=[('green', 'green'), ('red', 'red'), ('white', 'white')], default='white', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InRolik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roliktime', models.DateTimeField()),
                ('rolik_pay', models.PositiveIntegerField(default=10000)),
                ('status', models.CharField(choices=[('started', 'started'), ('going_on', 'going_on'), ('finished', 'finished')], default='finished', max_length=20)),
                ('rolik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inrolik', to='blogweb.rolik')),
            ],
        ),
    ]
