# Generated by Django 5.0.1 on 2024-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inrolik',
            name='roliktime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
