# Generated by Django 5.0.1 on 2024-01-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0002_alter_inrolik_roliktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolik',
            name='rolik_num',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
